name = "mi-app-hono"
compatibility_date = "2023-12-01"
main = "src/index.ts"

[vars]
SUPABASE_URL = "https://rmdlxyithpfdoemsajcs.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZGx4eWl0aHBmZG9lbXNhamNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1MTU5MjIsImV4cCI6MjA3OTA5MTkyMn0.aHqYIavBaEDCGg-MPI5D2X2T_wbXW7VpQyJ-xmumihI"
